# Generated by Django 2.1.2 on 2018-12-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_representation', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('english_representation',),
            },
        ),
    ]
